services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma-is-file-search
    ports:
      - "8000:8000"
    volumes:
      - ./hermes_db:/chroma
    command: "run --host 0.0.0.0 --port 8000 --path /chroma"
    environment:
      - IS_PERSISTENT=TRUE
    networks:
      - kkps-network

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-is-vector-search
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vector_search
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - kkps-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  kkps-network:
    external: true
